# github_repo_branch = "^(?=feature:DATPAY-)feature:DATPAY-([0-9]{4})$"
# github_repo_branch = "^feature:DATPAY-([0-9]{4})$"
environment = "dev"
github_repo_branch = "^dev$"
composer_gcs_bucket = "us-central1-pdh-composer-de-9fdde59d-bucket"
composer_environment = "pdh-composer-dev"
composer_location = "us-central1"
etl_bucket = "pdh_dev_etls"
# composer_project_id = "gcp-wow-wpay-paydat-dev"
# cloudBuild_serviceAcct = ""
# cloudBuild_logs = ""
terraform_backend_bucket = "gcp-wow-wpay-paydat-dev"
terraform_backend_prefix = "pdh-cicd/app"