insert into {{ trgt_table }}
select 
file_date,
file_name,
pdh_load_time,
payload_id,
status,
safe_cast(insert_seq_num AS NUMERIC),
safe_cast(mti AS NUMERIC),
pan,
safe_cast(txn_type_indicator AS NUMERIC),
safe_cast(currency_code_txn AS NUMERIC),
safe_cast(amount_txn AS NUMERIC),
safe_cast(curency_code_recn AS NUMERIC),
safe_cast(amount_recn AS NUMERIC),
safe_cast(currency_code_cb AS NUMERIC),
safe_cast(amount_cb AS NUMERIC),
safe_cast(txn_timestamp AS TIMESTAMP),
safe_cast(currency_code_cf AS NUMERIC),
safe_cast(amount_cf AS NUMERIC),
safe_cast(conv_rate_recn_network AS NUMERIC),
safe_cast(conv_rate_recn_acquirer AS NUMERIC),
safe_cast(conv_rate_recn_issuer AS NUMERIC),
safe_cast(conv_rate_cb AS NUMERIC),
safe_cast(sys_trace_audit_num AS NUMERIC),
safe_cast(local_timestamp AS TIMESTAMP),
effective_date,
expiry_date,
safe_cast(settlement_date AS DATE),
conv_date_acquirer,
conv_date_issuer,
capture_date,
safe_cast(ccode_acquiring_inst AS NUMERIC),
safe_cast(ccode_issuing_inst AS NUMERIC),
lifecycle_support_indicator,
lifecycle_trace_indicator,
lifecycle_seq_num,
safe_cast(lifecycle_token AS NUMERIC),
safe_cast(pos_card_data_input_method AS NUMERIC),
safe_cast(pos_cardholder_auth_method AS NUMERIC),
safe_cast(pos_operating_env AS NUMERIC),
safe_cast(pos_cardholder_present AS NUMERIC),
safe_cast(pos_card_present AS NUMERIC),
safe_cast(pos_cardholder_auth_entity AS NUMERIC),
safe_cast(card_seq_num AS NUMERIC),
safe_cast(function_code AS NUMERIC),
safe_cast(mssg_reason_code_acquirer AS NUMERIC),
safe_cast(merchant_cat_code AS NUMERIC),
pos_card_data_input_capability,
pos_cardholder_auth_capability,
pos_terminal_output_capability,
pos_card_data_output_capability,
pos_card_capture_capability,
pos_pin_capture_capability,
safe_cast(recn_date_acquirer AS DATE),
safe_cast(recn_date_issuer AS DATE),
safe_cast(original_ccode_txn AS NUMERIC),
safe_cast(original_amount_txn AS NUMERIC),
safe_cast(original_ccode_recn AS NUMERIC),
safe_cast(original_amount_recn AS NUMERIC),
safe_cast(acquirer_reference_num AS NUMERIC),
safe_cast(acquiring_institution_id AS NUMERIC),
safe_cast(forwarding_institution_id AS NUMERIC),
track_2_data,
retrieval_ref_num,
safe_cast(approval_code AS NUMERIC),
safe_cast(action_code AS NUMERIC),
service_code,
card_acceptor_terminal_id,
card_acceptor_id,
safe_cast(clerk_id AS NUMERIC),
card_acceptor_ccode,
safe_cast(card_acceptor_postal_code AS NUMERIC),
card_acceptor_region,
card_acceptor_name_location,
adtnl_response_data,
safe_cast(fee_type_code_1 AS NUMERIC),
safe_cast(fee_ccode_1 AS NUMERIC),
safe_cast(fee_amount_1 AS NUMERIC),
safe_cast(fee_conv_rate_acquirer_1 AS NUMERIC),
safe_cast(recn_fee_ccode_1 AS NUMERIC),
safe_cast(recn_fee_amount_1 AS NUMERIC),
safe_cast(fee_type_code_2 AS NUMERIC),
safe_cast(fee_ccode_2 AS NUMERIC),
safe_cast(fee_amount_2 AS NUMERIC),
safe_cast(fee_conv_rate_acquirer_2 AS NUMERIC),
safe_cast(recn_fee_ccode_2 AS NUMERIC),
safe_cast(recn_fee_amount_2 AS NUMERIC),
safe_cast(fee_type_code_3 AS NUMERIC),
safe_cast(fee_ccode_3 AS NUMERIC),
safe_cast(fee_amount_3 AS NUMERIC),
safe_cast(fee_conv_rate_acquirer_3 AS NUMERIC),
safe_cast(recn_fee_ccode_3 AS NUMERIC),
safe_cast(recn_fee_amount_3 AS NUMERIC),
safe_cast(fee_type_code_4 AS NUMERIC),
safe_cast(fee_ccode_4 AS NUMERIC),
safe_cast(fee_amount_4 AS NUMERIC),
safe_cast(fee_conv_rate_acquirer_4 AS NUMERIC),
safe_cast(recn_fee_ccode_4 AS NUMERIC),
safe_cast(recn_fee_amount_4 AS NUMERIC),
safe_cast(fee_type_code_5 AS NUMERIC),
safe_cast(fee_ccode_5 AS NUMERIC),
safe_cast(fee_amount_5 AS NUMERIC),
safe_cast(fee_conv_rate_acquirer_5 AS NUMERIC),
safe_cast(recn_fee_ccode_5 AS NUMERIC),
safe_cast(recn_fee_amount_5 AS NUMERIC),
safe_cast(fee_type_code_6 AS NUMERIC),
safe_cast(fee_ccode_6 AS NUMERIC),
safe_cast(fee_amount_6 AS NUMERIC),
safe_cast(fee_conv_rate_acquirer_6 AS NUMERIC),
safe_cast(recn_fee_ccode_6 AS NUMERIC),
safe_cast(recn_fee_amount_6 AS NUMERIC),
addtnl_data_acquirer,
addtnl_data_issuer,
cvv_cvc_result,
cvv2_cvc2_result,
cavv_result,
safe_cast(addtnl_request_accnt_type AS NUMERIC),
safe_cast(addtnl_request_amount_type AS NUMERIC),
safe_cast(addtnl_request_ccode AS NUMERIC),
safe_cast(addtnl_request_amount AS NUMERIC),
safe_cast(ode_mti AS NUMERIC),
safe_cast(ode_sys_trace_audit_num AS NUMERIC),
safe_cast(ode_timestamp AS TIMESTAMP),
safe_cast(ode_acquiring_inst_id AS NUMERIC),
safe_cast(auth_lifecycle_code AS NUMERIC),
ntwrk_terminal_id,
reporting_level_id,
ntwrk_id_acquirer,
ntwrk_id_issuer,
acquirer_processor_group_id,
issuer_processor_group_id,
processor_id_acquirer,
processor_id_issuer,
safe_cast(original_fee_type_code_1 AS NUMERIC),
safe_cast(original_fee_ccode_1 AS NUMERIC),
safe_cast(original_fee_amount_1 AS NUMERIC),
safe_cast(original_fee_conv_rate_acquirer_1 AS NUMERIC),
safe_cast(original_recn_fee_ccode_1 AS NUMERIC),
safe_cast(original_recn_fee_amount_1 AS NUMERIC),
safe_cast(original_fee_type_code_2 AS NUMERIC),
safe_cast(original_fee_ccode_2 AS NUMERIC),
safe_cast(original_fee_amount_2 AS NUMERIC),
safe_cast(original_fee_conv_rate_acquirer_2 AS NUMERIC),
safe_cast(original_recn_fee_ccode_2 AS NUMERIC),
safe_cast(original_recn_fee_amount_2 AS NUMERIC),
safe_cast(original_fee_type_code_3 AS NUMERIC),
safe_cast(original_fee_ccode_3 AS NUMERIC),
safe_cast(original_fee_amount_3 AS NUMERIC),
safe_cast(original_fee_conv_rate_acquirer_3 AS NUMERIC),
safe_cast(original_recn_fee_ccode_3 AS NUMERIC),
safe_cast(original_recn_fee_amount_3 AS NUMERIC),
safe_cast(original_fee_type_code_4 AS NUMERIC),
safe_cast(original_fee_ccode_4 AS NUMERIC),
safe_cast(original_fee_amount_4 AS NUMERIC),
safe_cast(original_fee_conv_rate_acquirer_4 AS NUMERIC),
safe_cast(original_recn_fee_ccode_4 AS NUMERIC),
safe_cast(original_recn_fee_amount_4 AS NUMERIC),
safe_cast(original_fee_type_code_5 AS NUMERIC),
safe_cast(original_fee_ccode_5 AS NUMERIC),
safe_cast(original_fee_amount_5 AS NUMERIC),
safe_cast(original_fee_conv_rate_acquirer_5 AS NUMERIC),
safe_cast(original_recn_fee_ccode_5 AS NUMERIC),
safe_cast(original_recn_fee_amount_5 AS NUMERIC),
safe_cast(original_fee_type_code_6 AS NUMERIC),
safe_cast(original_fee_ccode_6 AS NUMERIC),
safe_cast(original_fee_amount_6 AS NUMERIC),
safe_cast(original_fee_conv_rate_acquirer_6 AS NUMERIC),
safe_cast(original_recn_fee_ccode_6 AS NUMERIC),
safe_cast(original_recn_fee_amount_6 AS NUMERIC),
extended_pay_data,
action_date,
safe_cast(txn_dest_institution_id AS NUMERIC),
safe_cast(txn_origin_institution_id AS NUMERIC),
safe_cast(ref_data_issuer_format AS NUMERIC),
ref_data_issuer,
safe_cast(ccode_recn_acquirer AS NUMERIC),
safe_cast(amount_recn_acquirer AS NUMERIC),
safe_cast(ccode_recn_issuer AS NUMERIC),
safe_cast(amount_recn_issuer AS NUMERIC),
payee,
safe_cast(settlement_institution_id AS NUMERIC),
safe_cast(receiving_institution_id AS NUMERIC),
safe_cast(account_id_1 AS NUMERIC),
safe_cast(account_id_2 AS NUMERIC),
txn_desc,
safe_cast(txn_disposition AS NUMERIC),
auth_by,
safe_cast(terminal_class AS NUMERIC),
safe_cast(transaction_class AS NUMERIC),
role_flag,
safe_cast(accounting_type AS NUMERIC),
card_owner,
card_type
from {{ src_table }}